version: '3'
services:
  smw:
    build:
      context: .
      dockerfile: Dockerfile
    image: smw
    ports:
      - "2222:80"
    volumes:
      - wiki-images:/var/www/html/images
      - wiki-db:/var/www/data
      # After initial setup, download LocalSettings.php to this repo and uncomment the following line
      # use docker-compose to restart the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
volumes:
  wiki-images:
  wiki-db:
